/* 販売前レビュー対応 */
const localDate=(d=new Date())=>d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');
const validDate=v=>!v||/^\d{4}-\d{2}-\d{2}$/.test(v)&&!Number.isNaN(new Date(v+'T00:00:00').getTime());
const safeAddMonths=(value,amount)=>{if(!value||!validDate(value)||!Number.isInteger(amount)||amount<1)return'';const d=new Date(value+'T00:00:00'),day=d.getDate();d.setDate(1);d.setMonth(d.getMonth()+amount);d.setDate(Math.min(day,new Date(d.getFullYear(),d.getMonth()+1,0).getDate()));return localDate(d)};
const safeParseCycle=(cycle,custom='')=>{const fixed={毎月:{value:1,unit:'month'},'3か月':{value:3,unit:'month'},'6か月':{value:6,unit:'month'},'1年':{value:12,unit:'month'}}[cycle];if(fixed)return fixed;const m=String(custom).trim().match(/^(\d+)\s*(日|月|か月)$/);return m&&Number(m[1])>0?{value:Number(m[1]),unit:m[2]==='日'?'day':'month'}:null};
const safeCalc=(date,cycle,custom='')=>{const p=safeParseCycle(cycle,custom);if(!date||!p)return'';if(p.unit==='month')return safeAddMonths(date,p.value);const d=new Date(date+'T00:00:00');d.setDate(d.getDate()+p.value);return localDate(d)};
const safeDays=value=>value?Math.round((new Date(value+'T00:00:00')-new Date(localDate()+'T00:00:00'))/86400000):null;
const safeStatus=x=>{const n=safeDays(x.next),warn=Math.max(1,Number(localStorage.getItem('inspection-warn'))||30);return n===null?['期限未設定・要確認','near']:n<0?['期限超過','over']:n===0?['本日期限','over']:n<=7?['7日以内','near']:n<=14?['14日以内','near']:n<=warn?[warn+'日以内','near']:['正常','']};
table=rows=>rows.length?`<table><thead><tr><th>管理番号</th><th>対象名</th><th>分類</th><th>場所</th><th>次回期限</th><th>残り日数</th><th>担当者</th><th>状態</th></tr></thead><tbody>${rows.map(x=>{const s=safeStatus(x),n=safeDays(x.next);return`<tr data-id="${x.id}" class="${s[1]==='over'?'overdue':''}"><td>${esc(x.no)}</td><td>${esc(x.name)}</td><td>${esc(x.cat)}</td><td>${esc(x.place)}</td><td>${x.next||'未設定'}</td><td>${n===null?'要確認':n+'日'}</td><td>${esc(x.person)}</td><td><span class="badge ${s[1]}">${s[0]}</span></td></tr>`}).join('')}</tbody></table>`:'<p class="muted">登録データはありません。</p>';
dash=()=>{const m=localDate().slice(0,7);app.innerHTML=`<div class="grid"><div class="card">登録件数<b>${items.length}</b></div><div class="card">今月点検予定<b>${items.filter(x=>x.next?.startsWith(m)).length}</b></div><div class="card">期限7日以内<b class="near">${items.filter(x=>safeDays(x.next)!==null&&safeDays(x.next)>=0&&safeDays(x.next)<=7).length}</b></div><div class="card">期限超過<b class="danger">${items.filter(x=>safeDays(x.next)!==null&&safeDays(x.next)<0).length}</b></div><div class="card">期限未設定<b>${items.filter(x=>!x.next).length}</b></div></div><div class="panel"><h2>近日期限</h2>${table(items.slice().sort((a,b)=>(safeDays(a.next)??999999)-(safeDays(b.next)??999999)).slice(0,10))}</div>`};
const validItem=x=>x&&typeof x==='object'&&typeof x.id==='string'&&x.id&&typeof x.name==='string'&&typeof x.cat==='string'&&validDate(x.prev||'')&&validDate(x.next||'')&&Array.isArray(x.history||[]);
sample.onclick=()=>{if(items.length){alert('登録済みデータがあるためサンプルは読み込みません。JSONバックアップ後に空の状態でお試しください。');return}items=[{id:'s1',no:'CHK-0001',name:'SAMPLE車両01',cat:'車両',place:'SAMPLE拠点',person:'Staff A',task:'定期点検',prev:localDate(),next:safeAddMonths(localDate(),1),cycle:'毎月',customCycle:'',history:[]}];try{save();show('dash')}catch(e){items=[];alert('保存できませんでした。既存データは変更していません。')}};
const oldBackup=backup;backup=()=>{oldBackup();const p=document.createElement('p');p.className='muted';p.textContent='JSONは全データ・履歴の保全用です。CSVには履歴と設定が含まれません。';app.querySelector('.panel').appendChild(p);ji.onchange=async()=>{const f=ji.files?.[0];if(!f)return;const before=localStorage.getItem(KEY);try{const parsed=JSON.parse((await f.text()).replace(/^\uFEFF/,''));const incoming=Array.isArray(parsed)?parsed:parsed?.items;if(!Array.isArray(incoming)||!incoming.every(validItem))throw Error('必須項目・型・日付を確認してください');if(!confirm(incoming.length+'件で現在の'+items.length+'件を置き換えます。復元前データを自動退避します。続けますか？'))return;localStorage.setItem(KEY+'-before-restore',before||'[]');localStorage.setItem(KEY,JSON.stringify(incoming));items=incoming;show('dash')}catch(e){if(before===null)localStorage.removeItem(KEY);else localStorage.setItem(KEY,before);alert('復元できません。既存データは維持されています。\n'+e.message)}}};
window.reviewDateTools={localDate,safeAddMonths,safeCalc};

form=(id='')=>{
  const existing=items.find(a=>a.id===id);
  const x=existing||{cat:cats[0],cycle:'6か月',customCycle:'',history:[]};
  const configuredCats=(localStorage.getItem('inspection-cats')||cats.join(',')).split(',').map(v=>v.trim()).filter(Boolean);
  if(x.cat&&!configuredCats.includes(x.cat))configuredCats.push(x.cat);
  const people=(localStorage.getItem('inspection-people')||'Staff A,Staff B').split(',').map(v=>v.trim()).filter(Boolean);
  app.innerHTML=`<div class="panel"><h2>${id?'点検対象を編集':'新規登録'}</h2><div class="form"><label>対象名<input id="name" value="${esc(x.name)}" required></label><label>分類<select id="cat">${configuredCats.map(c=>`<option ${c===x.cat?'selected':''}>${esc(c)}</option>`).join('')}</select></label><label>管理場所<input id="place" value="${esc(x.place)}"></label><label>担当者<input id="person" list="peopleList" value="${esc(x.person)}"><datalist id="peopleList">${people.map(v=>`<option value="${esc(v)}">`).join('')}</datalist></label><label>点検・作業名称<input id="task" value="${esc(x.task)}" required></label><label>前回実施日<input id="prev" type="date" value="${x.prev||''}"></label><label>点検周期<select id="cycle">${cycles.map(c=>`<option ${c===x.cycle?'selected':''}>${c}</option>`).join('')}</select></label><label id="customLabel">任意周期（90日／2か月）<input id="customCycle" value="${esc(x.customCycle||'')}"></label><label>次回期限<input id="next" type="date" value="${x.next||''}"></label><label class="wide">備考<textarea id="note">${esc(x.note)}</textarea></label></div><div class="actions"><button id="auto">期限を自動計算</button><button id="complete">点検完了</button><button id="saveBtn">保存</button>${id?'<button id="del" class="danger">削除</button>':''}<button id="cancelBtn">キャンセル</button></div><div id="completeBox"></div></div>`;
  const [name,cat,place,person,task,prev,cycle,customCycle,next,note,customLabel,auto,saveBtn,cancelBtn,complete,completeBox,del]=['name','cat','place','person','task','prev','cycle','customCycle','next','note','customLabel','auto','saveBtn','cancelBtn','complete','completeBox','del'].map(v=>document.getElementById(v));
  const updateCustom=()=>customLabel.style.display=cycle.value==='任意設定'?'grid':'none';cycle.onchange=updateCustom;updateCustom();
  auto.onclick=()=>{const value=safeCalc(prev.value,cycle.value,customCycle.value);if(!value){alert('前回実施日と有効な周期を入力してください。任意周期は90日または2か月の形式です。');return}next.value=value};
  const collect=()=>({id:id||crypto.randomUUID(),no:x.no||`CHK-${String(items.length+1).padStart(4,'0')}`,name:name.value.trim(),cat:cat.value,place:place.value.trim(),person:person.value.trim(),task:task.value.trim(),prev:prev.value,next:next.value,cycle:cycle.value,customCycle:cycle.value==='任意設定'?customCycle.value.trim():'',note:note.value,history:x.history||[]});
  const validate=n=>{if(!n.name||!n.task){alert('対象名と点検・作業名称は必須です。');return false}if(n.cycle==='任意設定'&&!safeParseCycle(n.cycle,n.customCycle)){alert('任意周期は1以上の「日」または「か月」で入力してください。');return false}if(!validDate(n.prev)||!validDate(n.next)){alert('日付の形式が正しくありません。');return false}return true};
  saveBtn.onclick=()=>{const n=collect();if(!validate(n))return;const nextItems=id?items.map(a=>a.id===id?n:a):[...items,n];try{localStorage.setItem(KEY,JSON.stringify(nextItems));items=nextItems;show('list')}catch(e){alert('保存できませんでした。既存データは変更していません。')}};
  cancelBtn.onclick=()=>show(id?'list':'dash');
  complete.onclick=()=>{const draft=collect();if(!validate(draft))return;completeBox.innerHTML=`<div class="panel"><h3>点検完了内容</h3><div class="form"><label>実施日<input id="doneDate" type="date" value="${localDate()}"></label><label>担当者<input id="donePerson" value="${esc(draft.person)}"></label><label class="wide">作業内容<textarea id="doneTask">${esc(draft.task)}</textarea></label><label class="wide">不具合・問題内容<textarea id="doneIssue"></textarea></label><label class="wide">実施した対応<textarea id="doneAction"></textarea></label><label class="wide">改善策<textarea id="doneImprove"></textarea></label></div><button id="confirmDone">確認して保存</button><button id="cancelDone">キャンセル</button></div>`;cancelDone.onclick=()=>completeBox.innerHTML='';let busy=false;confirmDone.onclick=()=>{if(busy)return;const date=doneDate.value,cycleInfo=safeParseCycle(draft.cycle,draft.customCycle);if(!date||!donePerson.value.trim()||!doneTask.value.trim()||!cycleInfo){alert('実施日・担当者・作業内容・有効な周期を確認してください。');return}if(!confirm('表示内容で点検完了を保存しますか？'))return;busy=true;const record={...draft,prev:date,next:safeCalc(date,draft.cycle,draft.customCycle),history:[...(draft.history||[]),{id:crypto.randomUUID(),date,task:doneTask.value.trim(),person:donePerson.value.trim(),issue:doneIssue.value,action:doneAction.value,improve:doneImprove.value,next:safeCalc(date,draft.cycle,draft.customCycle)}]};const nextItems=id?items.map(a=>a.id===id?record:a):[...items,record];try{localStorage.setItem(KEY,JSON.stringify(nextItems));items=nextItems;show('list')}catch(e){busy=false;alert('保存できませんでした。既存データは変更していません。')}}
  if(id)del.onclick=()=>{if(confirm('この対象と履歴を削除しますか？')){const nextItems=items.filter(a=>a.id!==id);try{localStorage.setItem(KEY,JSON.stringify(nextItems));items=nextItems;show('list')}catch(e){alert('削除を保存できませんでした。')}}};
};
};
schedule=()=>{const current=localDate().slice(0,7);app.innerHTML=`<div class="panel"><h2>点検予定</h2><label>表示月<input id="scheduleMonth" type="month" value="${current}"></label><button id="nextMonth">翌月</button><div id="scheduleRows"></div></div>`;const render=()=>scheduleRows.innerHTML=table(items.filter(x=>x.next?.startsWith(scheduleMonth.value)));scheduleMonth.onchange=render;nextMonth.onclick=()=>{scheduleMonth.value=safeAddMonths(scheduleMonth.value+'-01',1).slice(0,7);render()};render()};
const applyOrgName=()=>{const name=localStorage.getItem('inspection-org')?.trim();document.querySelector('aside h1').textContent=name?name+'｜点検期限管理':'点検期限管理'};applyOrgName();
const settingsBaseReview=settings;settings=()=>{settingsBaseReview();const saveButton=document.getElementById('saveSettings');if(saveButton)saveButton.addEventListener('click',applyOrgName)};
