const KEY='store-handoff-v1';let data=JSON.parse(localStorage.getItem(KEY)||'null')||[];let editing=null;const cats=['お客様対応','クレーム','事故・トラブル','設備','車両','社内連絡','その他'];const statuses=['未対応','対応中','完了'];const today=()=>new Date().toISOString().slice(0,10);const save=()=>localStorage.setItem(KEY,JSON.stringify(data));const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const overdue=x=>x.due&&x.due<today()&&x.status!=='完了';
function dash(){const c=s=>data.filter(x=>x.status===s).length;app.innerHTML=`<div class="grid"><div class="card">未対応<b class="danger">${c('未対応')}</b></div><div class="card">対応中<b class="warn">${c('対応中')}</b></div><div class="card">完了<b class="ok">${c('完了')}</b></div><div class="card">期限超過<b class="danger">${data.filter(overdue).length}</b></div><div class="card">本日の登録<b>${data.filter(x=>x.created.slice(0,10)===today()).length}</b></div></div><div class="panel"><h2>最近の申し送り</h2>${table(data.slice().sort((a,b)=>b.created.localeCompare(a.created)).slice(0,5))}</div>`}
function table(rows){return `<table><thead><tr><th>管理番号</th><th>発生日</th><th>件名</th><th>分類</th><th>重要度</th><th>担当者</th><th>対応期限</th><th>状況</th></tr></thead><tbody>${rows.map(x=>`<tr class="${overdue(x)?'overdue':''}" data-id="${x.id}"><td>${x.no}</td><td>${x.date}</td><td>${esc(x.subject)}</td><td>${x.cat}</td><td>${x.priority}</td><td>${esc(x.person)}</td><td>${x.due||''}</td><td class="status ${x.status}">${x.status}${overdue(x)?' ⚠':''}</td></tr>`).join('')}</tbody></table>`}
function list(){app.innerHTML=`<div class="panel"><div class="form"><label>検索<input id="q" placeholder="件名・内容・担当者"></label><label>状況<select id="fs"><option value="">すべて</option>${statuses.map(x=>`<option>${x}</option>`)}</select></label></div><div class="actions"><button id="un" class="secondary">未対応のみ</button><button id="ov" class="secondary">期限超過のみ</button></div><div id="rows" style="margin-top:16px"></div></div>`;const render=()=>{let r=data.filter(x=>(!q.value||JSON.stringify(x).includes(q.value))&&(!fs.value||x.status===fs.value));if(window.only==='un')r=r.filter(x=>x.status!=='完了');if(window.only==='ov')r=r.filter(overdue);rows.innerHTML=table(r);rows.querySelectorAll('tr[data-id]').forEach(e=>e.onclick=()=>form(e.dataset.id))};q.oninput=render;fs.onchange=render;un.onclick=()=>{window.only='un';render()};ov.onclick=()=>{window.only='ov';render()};render()}
function form(id=''){const x=data.find(a=>a.id===id)||{date:today(),status:'未対応',priority:'通常',cat:cats[0],person:'',due:'',subject:'',content:'',response:'',improve:''};editing=id;app.innerHTML=`<div class="panel"><h2>${id?'申し送り詳細':'新規登録'}</h2><div class="form">${id?`<label>管理番号<input value="${x.no}" disabled></label>`:''}<label>発生日<input id="date" type="date" value="${x.date}"></label><label>件名<input id="subject" value="${esc(x.subject)}"></label><label>分類<select id="cat">${cats.map(v=>`<option ${v===x.cat?'selected':''}>${v}</option>`)}</select></label><label>重要度<select id="priority">${['低','通常','高','緊急'].map(v=>`<option ${v===x.priority?'selected':''}>${v}</option>`)}</select></label><label>担当者<input id="person" value="${esc(x.person)}"></label><label>対応期限<input id="due" type="date" value="${x.due}"></label><label>対応状況<select id="status">${statuses.map(v=>`<option ${v===x.status?'selected':''}>${v}</option>`)}</select></label><label class="wide">内容<textarea id="content">${esc(x.content)}</textarea></label><label class="wide">対応内容<textarea id="response">${esc(x.response)}</textarea></label><label class="wide">改善策<textarea id="improve">${esc(x.improve)}</textarea></label></div><div class="actions"><button id="saveBtn">保存</button>${id?'<button id="del" class="dangerBtn">削除</button>':''}<button id="back" class="secondary">戻る</button></div></div>`;saveBtn.onclick=()=>{const n={id:id||crypto.randomUUID(),no:x.no||`MSG-${String(data.length+1).padStart(4,'0')}`,created:x.created||new Date().toISOString(),completed:status.value==='完了'?(x.completed||new Date().toISOString()):'',date:date.value,subject:subject.value,cat:cat.value,priority:priority.value,person:person.value,due:due.value,status:status.value,content:content.value,response:response.value,improve:improve.value};if(id)data[data.findIndex(a=>a.id===id)]=n;else data.push(n);save();view('list')};back.onclick=()=>view('list');if(id)del.onclick=()=>{if(confirm('削除しますか？')){data=data.filter(a=>a.id!==id);save();view('list')}}}
function improvements(){const rows=data.filter(x=>x.status==='完了'&&x.improve);app.innerHTML=`<div class="panel"><h2>改善策一覧</h2>${rows.length?rows.map(x=>`<article class="card"><b>${x.date}｜${x.cat}｜${esc(x.subject)}</b><p>${esc(x.content)}</p><p><strong>改善策：</strong>${esc(x.improve)}</p><small>担当者：${esc(x.person)}</small></article>`).join(''):'改善策はまだありません。'}</div>`}
function backup(){app.innerHTML=`<div class="panel"><h2>バックアップ</h2><p>データをJSONまたはCSVで保存・復元できます。</p><div class="actions"><button id="jsonOut">JSON保存</button><button id="csvOut">CSV保存</button><label class="button secondary">JSON復元<input id="jsonIn" type="file" accept=".json" hidden></label><label class="button secondary">CSV復元<input id="csvIn" type="file" accept=".csv" hidden></label></div></div>`;const dl=(name,text,type)=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\uFEFF',text],{type}));a.download=name;a.click()};jsonOut.onclick=()=>dl('申し送りバックアップ.json',JSON.stringify(data,null,2),'application/json');csvOut.onclick=()=>dl('申し送り一覧.csv',['管理番号,発生日,件名,分類,重要度,担当者,対応期限,対応状況,内容,対応内容,改善策',...data.map(x=>[x.no,x.date,x.subject,x.cat,x.priority,x.person,x.due,x.status,x.content,x.response,x.improve].map(v=>`"${String(v||'').replaceAll('"','""')}"`).join(','))].join('\r\n'),'text/csv');jsonIn.onchange=async()=>{if(confirm('現在のデータを置き換えますか？')){data=JSON.parse(await jsonIn.files[0].text());save();view('dashboard')}}}
function view(v){viewTitle.textContent={dashboard:'ダッシュボード',list:'申し送り一覧',form:'新規登録',improvements:'改善策一覧',backup:'バックアップ'}[v]||v;({dashboard:dash,list,form,improvements,backup}[v])()}document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>view(b.dataset.view));sampleBtn.onclick=()=>{data=[{id:'s1',no:'MSG-0001',created:new Date().toISOString(),date:today(),subject:'空調設備の確認',cat:'設備',priority:'高',person:'Staff A',due:today(),status:'未対応',content:'客室の空調を確認する。',response:'',improve:''},{id:'s2',no:'MSG-0002',created:new Date().toISOString(),date:today(),subject:'備品補充',cat:'社内連絡',priority:'通常',person:'Staff B',due:'',status:'完了',content:'備品を補充。',response:'対応済み',improve:'毎週月曜に在庫確認'}];save();view('dashboard')};view('dashboard');
// CSV復元の補助処理（引用符・カンマ・改行を含むセルに対応）
function parseCsvText(text){const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const ch=text[i],next=text[i+1];if(quoted){if(ch==='"'&&next==='"'){cell+='"';i++;}else if(ch==='"')quoted=false;else cell+=ch;}else if(ch==='"')quoted=true;else if(ch===','){row.push(cell);cell='';}else if(ch==='\n'){row.push(cell.replace(/\r$/,''));rows.push(row);row=[];cell='';}else cell+=ch;}if(cell!==''||row.length){row.push(cell.replace(/\r$/,''));rows.push(row);}return rows;}

// CSV復元入力のイベントを追加（旧版で未接続だった場合にも有効）
const csvRestoreInput=document.getElementById('csvIn');
if(csvRestoreInput)csvRestoreInput.addEventListener('change',async()=>{const f=csvRestoreInput.files?.[0];if(!f)return;try{const rows=parseCsvText((await f.text()).replace(/^\uFEFF/,''));if(rows.length<2)throw Error();const h=Object.fromEntries(rows[0].map((v,i)=>[v.trim(),i]));const req=['管理番号','発生日','件名','分類','重要度','担当者','対応期限','対応状況'];if(req.some(k=>h[k]===undefined))throw Error();const imported=rows.slice(1).filter(r=>r.some(v=>v.trim())).map((r,n)=>({id:crypto.randomUUID(),no:r[h['管理番号']]||`MSG-${String(n+1).padStart(4,'0')}`,created:new Date().toISOString(),date:r[h['発生日']]||'',subject:r[h['件名']]||'',cat:r[h['分類']]||'その他',priority:r[h['重要度']]||'通常',person:r[h['担当者']]||'',due:r[h['対応期限']]||'',status:r[h['対応状況']]||'未対応',content:r[h['内容']]||'',response:r[h['対応内容']]||'',improve:r[h['改善策']]||'',completed:''}));if(!imported.length||!confirm(`${imported.length}件のCSVデータで現在のデータを置き換えますか？`))return;data=imported;save();view('dashboard');}catch(e){alert('CSVを読み込めませんでした。アプリのCSV出力形式を確認してください。')}});

// バックアップ画面を開いた後にCSV復元イベントを接続する。
const backupBase=backup;
backup=function(){backupBase();csvIn.onchange=async()=>{const f=csvIn.files?.[0];if(!f)return;try{const rows=parseCsvText((await f.text()).replace(/^\uFEFF/,''));if(rows.length<2)throw Error();const h=Object.fromEntries(rows[0].map((v,i)=>[v.trim(),i]));const req=['管理番号','発生日','件名','分類','重要度','担当者','対応期限','対応状況'];if(req.some(k=>h[k]===undefined))throw Error();const imported=rows.slice(1).filter(r=>r.some(v=>v.trim())).map((r,n)=>({id:crypto.randomUUID(),no:r[h['管理番号']]||`MSG-${String(n+1).padStart(4,'0')}`,created:new Date().toISOString(),date:r[h['発生日']]||'',subject:r[h['件名']]||'',cat:r[h['分類']]||'その他',priority:r[h['重要度']]||'通常',person:r[h['担当者']]||'',due:r[h['対応期限']]||'',status:r[h['対応状況']]||'未対応',content:r[h['内容']]||'',response:r[h['対応内容']]||'',improve:r[h['改善策']]||'',completed:''}));if(!imported.length||!confirm(`${imported.length}件のCSVデータで現在のデータを置き換えますか？`))return;data=imported;save();view('dashboard');}catch(e){alert('CSVを読み込めませんでした。アプリのCSV出力形式を確認してください。')}}};
const cloudLink=document.createElement('a');cloudLink.href='クラウド共有.html';cloudLink.textContent='クラウド共有';cloudLink.style.cssText='display:block;color:#dbe7f7;padding:13px 14px;text-decoration:none';document.querySelector('nav').appendChild(cloudLink);
