/* 販売前レビュー対応 */
const businessDate=(d=new Date())=>d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');
sampleBtn.onclick=()=>{if(data.length){alert('登録済みデータがあるためサンプルは読み込みません。JSONバックアップ後に空の状態でお試しください。');return}data=[{id:'s1',no:'MSG-0001',created:new Date().toISOString(),date:businessDate(),subject:'SAMPLE設備の確認',cat:'設備',priority:'高',person:'Staff A',due:businessDate(),status:'未対応',content:'架空の確認事項です。',response:'',improve:''}];try{save();view('dashboard')}catch(e){data=[];alert('保存できませんでした。既存データは変更していません。')}};
list=()=>{window.only='';app.innerHTML=`<div class="panel"><div class="form"><label>検索<input id="q" placeholder="件名・内容・担当者"></label><label>状況<select id="fs"><option value="">すべて</option>${statuses.map(x=>`<option>${x}</option>`)}</select></label></div><div class="actions"><button id="un" class="secondary">未完了のみ</button><button id="ov" class="secondary">期限超過のみ</button><button id="clearFilter" class="secondary">絞り込み解除</button></div><p id="filterState" class="muted">適用中：条件なし</p><div id="rows" style="margin-top:16px"></div></div>`;const render=()=>{let r=data.filter(x=>(!q.value||JSON.stringify(x).includes(q.value))&&(!fs.value||x.status===fs.value));if(window.only==='un')r=r.filter(x=>x.status!=='完了');if(window.only==='ov')r=r.filter(overdue);filterState.textContent='適用中：'+[q.value&&'検索「'+q.value+'」',fs.value&&'状況 '+fs.value,window.only==='un'&&'未完了のみ',window.only==='ov'&&'期限超過のみ'].filter(Boolean).join('／')||'適用中：条件なし';rows.innerHTML=table(r);rows.querySelectorAll('tr[data-id]').forEach(e=>e.onclick=()=>form(e.dataset.id))};q.oninput=render;fs.onchange=render;un.onclick=()=>{window.only='un';render()};ov.onclick=()=>{window.only='ov';render()};clearFilter.onclick=()=>{q.value='';fs.value='';window.only='';render()};render()};
const validRecord=x=>x&&typeof x==='object'&&typeof x.id==='string'&&x.id&&typeof x.subject==='string'&&typeof x.status==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(x.date||'');
const oldBackupSafe=backup;backup=()=>{oldBackupSafe();const p=document.createElement('p');p.className='muted';p.textContent='JSONは全項目の保全用です。CSVは一覧交換用で、設定等は含まれません。';app.querySelector('.panel').appendChild(p);jsonIn.onchange=async()=>{const f=jsonIn.files?.[0];if(!f)return;const before=localStorage.getItem(KEY);try{const parsed=JSON.parse((await f.text()).replace(/^\uFEFF/,''));const incoming=Array.isArray(parsed)?parsed:parsed?.data;if(!Array.isArray(incoming)||!incoming.every(validRecord))throw Error('必須項目・型・日付を確認してください');if(!confirm(incoming.length+'件で現在の'+data.length+'件を置き換えます。復元前データを自動退避します。続けますか？'))return;localStorage.setItem(KEY+'-before-restore',before||'[]');localStorage.setItem(KEY,JSON.stringify(incoming));data=incoming;view('dashboard')}catch(e){if(before===null)localStorage.removeItem(KEY);else localStorage.setItem(KEY,before);alert('復元できません。既存データは維持されています。\n'+e.message)}}};

const businessOverdue=x=>x.due&&x.due<businessDate()&&x.status!=='完了';
dash=()=>{const c=s=>data.filter(x=>x.status===s).length;app.innerHTML=`<div class="grid"><div class="card">未対応<b class="danger">${c('未対応')}</b></div><div class="card">対応中<b class="warn">${c('対応中')}</b></div><div class="card">完了<b class="ok">${c('完了')}</b></div><div class="card">期限超過<b class="danger">${data.filter(overdue).length}</b></div><div class="card">本日の登録<b>${data.filter(x=>(x.date||'')===businessDate()).length}</b></div></div><div class="panel"><h2>最近の申し送り</h2>${table(data.slice().sort((a,b)=>b.created.localeCompare(a.created)).slice(0,5))}</div>`};

const originalForm=form;
form=(id='')=>{originalForm(id);const panel=app.querySelector('.panel'),backBtn=document.getElementById('back');if(!panel)return;let dirty=false;panel.querySelectorAll('input,textarea,select').forEach(el=>el.addEventListener('input',()=>dirty=true));if(backBtn)backBtn.onclick=()=>{if(!dirty||confirm('入力中の変更を破棄して一覧へ戻りますか？'))view('list')};if(id){const print=document.createElement('button');print.textContent='この案件を印刷';print.className='secondary';print.onclick=()=>{sessionStorage.setItem('store-print-id',id);location.href='印刷用テンプレート.html?id='+encodeURIComponent(id)};panel.querySelector('.actions').appendChild(print)}};
